# Penguin Multivariable Linear Regression with Data Normalization
带有数据归一化的线性回归

In [63]:
# read the variables: class label and features

def string2float(item):
    return float(item) if item != '' else None

def read_strings(filename, col):
    with open(filename) as f:
        lines = f.readlines()
    values = [line.strip().split(',')[col] for line in lines[1:]]
    return values

def read_floats(filename, col):
    with open(filename) as f:
        lines = f.readlines()
    values = [string2float(line.strip().split(',')[col]) for line in lines[1:]]
    return values

In [65]:
import numpy as np

filename = 'data/palmer-penguins/palmer-penguins-train.txt'

x1 = np.array(read_floats(filename, col=2))
x2 = np.array(read_floats(filename, col=3))
x3 = np.array(read_floats(filename, col=4))

y = np.array(read_floats(filename, col=5))

In [67]:
idx = (x1 != None) & (x2 != None) & (x3 != None) & (y != None)

x1 = x1[idx]
x2 = x2[idx]
x3 = x3[idx]

y = y[idx]

In [69]:
# Min-Max
#拼接x1，x2，x3
X = np.stack((x1, x2, x3), axis=1)

X_min = np.min(X, axis=0)
X_max = np.max(X, axis=0)

print(X_min)
print(X_max)
print(np.finfo(float).eps)

X = (X - X_min)/(X_max - X_min + np.finfo(float).eps)
print(X[:10])

[ 32.1  13.1 172. ]
[ 52.7  21.1 222. ]
2.220446049250313e-16
[[0.33980583 0.7        0.18      ]
 [0.39805825 0.6125     0.46      ]
 [0.22330097 0.775      0.42      ]
 [0.33009709 0.5875     0.18      ]
 [0.09708738 0.625      0.42      ]
 [0.27669903 0.5        0.28      ]
 [0.4368932  0.5625     0.2       ]
 [0.12135922 1.         0.52      ]
 [0.32038835 0.7375     0.46      ]
 [0.11165049 0.6625     0.24      ]]


In [71]:
x0 = np.ones((x1.shape[0], 1))
print(x0.shape)
#加上偏置
print(X.shape)

X = np.concatenate((x0, X), axis=1)
print(X.shape)
print(X[:10])

(172, 1)
(172, 3)
(172, 4)
[[1.         0.33980583 0.7        0.18      ]
 [1.         0.39805825 0.6125     0.46      ]
 [1.         0.22330097 0.775      0.42      ]
 [1.         0.33009709 0.5875     0.18      ]
 [1.         0.09708738 0.625      0.42      ]
 [1.         0.27669903 0.5        0.28      ]
 [1.         0.4368932  0.5625     0.2       ]
 [1.         0.12135922 1.         0.52      ]
 [1.         0.32038835 0.7375     0.46      ]
 [1.         0.11165049 0.6625     0.24      ]]


In [73]:
result = np.matmul(X.transpose(), X)
result = np.linalg.inv(result)
result = np.matmul(result, X.transpose())
result = np.matmul(result, y)
w = result

print(w)

[2836.65586543  163.121665   -266.14753242 2100.14533999]


In [75]:
# training set evaluation

y_pred = np.matmul(X, w)

diff = y - y_pred
mse = np.mean(diff ** 2)

print(mse)
print(np.mean(y), np.sqrt(mse), np.sqrt(mse)/np.mean(y))

110130.75361723578
3903.343023255814 331.85953898786124 0.08501931216669095


$\mathbf{x} = [x_0, x_1, x_2, x_3]$ vs. $\mathbf{x} = [x_0, x_1]$

3903.343023255814 335.57111934278447 0.08597018436337207

In [79]:
# test data

filename = 'data/palmer-penguins/palmer-penguins-test.txt'

x1 = np.array(read_floats(filename, col=2))
x2 = np.array(read_floats(filename, col=3))
x3 = np.array(read_floats(filename, col=4))

y = np.array(read_floats(filename, col=5))

idx = (x1 != None) & (x2 != None) & (x3 != None) & (y != None)

x1 = x1[idx]
x2 = x2[idx]
x3 = x3[idx]

y = y[idx]

In [83]:
# Min-Max

X = np.stack((x1, x2, x3), axis=1)

X = (X - X_min)/(X_max - X_min + np.finfo(float).eps)
print(X[:10])

[[0.3592233009708737 0.5374999999999998 0.28]
 [0.3495145631067959 0.9375 0.36]
 [0.34466019417475735 0.8125 0.46]
 [0.48058252427184456 0.8874999999999997 0.36]
 [0.27669902912621336 0.525 0.16]
 [0.31553398058252424 1.0124999999999997 0.38]
 [0.21844660194174756 0.5875 0.26]
 [0.5048543689320387 0.9499999999999997 0.5]
 [0.674757281553398 1.0499999999999998 0.44]
 [0.2718446601941748 0.6999999999999998 0.16]]


In [85]:
x0 = np.ones((x1.shape[0], 1))
print(x0.shape)

print(X.shape)

X = np.concatenate((x0, X), axis=1)
print(X.shape)
print(X[:10])

(170, 1)
(170, 3)
(170, 4)
[[1.0 0.3592233009708737 0.5374999999999998 0.28]
 [1.0 0.3495145631067959 0.9375 0.36]
 [1.0 0.34466019417475735 0.8125 0.46]
 [1.0 0.48058252427184456 0.8874999999999997 0.36]
 [1.0 0.27669902912621336 0.525 0.16]
 [1.0 0.31553398058252424 1.0124999999999997 0.38]
 [1.0 0.21844660194174756 0.5875 0.26]
 [1.0 0.5048543689320387 0.9499999999999997 0.5]
 [1.0 0.674757281553398 1.0499999999999998 0.44]
 [1.0 0.2718446601941748 0.6999999999999998 0.16]]


In [87]:
y_pred = np.matmul(X, w)

diff = y - y_pred
mse = np.mean(diff ** 2)

print(mse)
print(np.mean(y), np.sqrt(mse), np.sqrt(mse)/np.mean(y))

287525.73963547655
4503.676470588235 536.2142665348215 0.11906145346732364


$\mathbf{x} = [x_0, x_1, x_2, x_3]$ vs. $\mathbf{x} = [x_0, x_1]$

4503.676470588235 506.7945019577786 0.11252906492450268