# Penguin Multivariable Linear Regression
这里采用的是多变量

In [1]:
# read the variables: class label and features

def string2float(item):
    return float(item) if item != '' else None

def read_strings(filename, col):
    with open(filename) as f:
        lines = f.readlines()
    values = [line.strip().split(',')[col] for line in lines[1:]]
    return values

def read_floats(filename, col):
    with open(filename) as f:
        lines = f.readlines()
    values = [string2float(line.strip().split(',')[col]) for line in lines[1:]]
    return values

In [2]:
import numpy as np

filename = '/Users/liubingyi/Documents/learn/data/palmer-penguins-test.txt'

x1 = np.array(read_floats(filename, col=2))
x2 = np.array(read_floats(filename, col=3))
x3 = np.array(read_floats(filename, col=4))

y = np.array(read_floats(filename, col=5))

In [3]:
idx = (x1 != None) & (x2 != None) & (x3 != None) & (y != None)

x1 = x1[idx]
x2 = x2[idx]
x3 = x3[idx]

y = y[idx]

x0 = np.ones(x1.shape)

In [6]:
X = np.stack((x0, x1, x2, x3), axis=1)

print(X.shape)
print(X[:10])

(170, 4)
[[1.0 39.5 17.4 186.0]
 [1.0 39.3 20.6 190.0]
 [1.0 39.2 19.6 195.0]
 [1.0 42.0 20.2 190.0]
 [1.0 37.8 17.3 180.0]
 [1.0 38.6 21.2 191.0]
 [1.0 36.6 17.8 185.0]
 [1.0 42.5 20.7 197.0]
 [1.0 46.0 21.5 194.0]
 [1.0 37.7 18.7 180.0]]


In [7]:
result = np.matmul(X.transpose(), X)
result = np.linalg.inv(result)
result = np.matmul(result, X.transpose())
result = np.matmul(result, y)
w = result

print(w)

UFuncTypeError: Cannot cast ufunc 'inv' input from dtype('O') to dtype('float64') with casting rule 'same_kind'

In [49]:
# training set evaluation

y_pred = np.matmul(X, w)

diff = y - y_pred
mse = np.mean(diff ** 2)

print(mse)
print(np.mean(y), np.sqrt(mse), np.sqrt(mse)/np.mean(y))

110130.75361723576
3903.343023255814 331.8595389878612 0.08501931216669094


$\mathbf{x} = [x_0, x_1, x_2, x_3]$ vs. $\mathbf{x} = [x_0, x_1]$

3903.343023255814 335.57111934278447 0.08597018436337207

In [52]:
# test data

filename = 'data/palmer-penguins/palmer-penguins-test.txt'

x1 = np.array(read_floats(filename, col=2))
x2 = np.array(read_floats(filename, col=3))
x3 = np.array(read_floats(filename, col=4))

y = np.array(read_floats(filename, col=5))

idx = (x1 != None) & (x2 != None) & (x3 != None) & (y != None)

x1 = x1[idx]
x2 = x2[idx]
x3 = x3[idx]

y = y[idx]

x0 = np.ones(x1.shape)

X = np.stack((x0, x1, x2, x3), axis=1)

print(X.shape)
print(X[:10])

(170, 4)
[[1.0 39.5 17.4 186.0]
 [1.0 39.3 20.6 190.0]
 [1.0 39.2 19.6 195.0]
 [1.0 42.0 20.2 190.0]
 [1.0 37.8 17.3 180.0]
 [1.0 38.6 21.2 191.0]
 [1.0 36.6 17.8 185.0]
 [1.0 42.5 20.7 197.0]
 [1.0 46.0 21.5 194.0]
 [1.0 37.7 18.7 180.0]]


In [18]:
y_pred = np.matmul(X, w)

diff = y - y_pred
mse = np.mean(diff ** 2)

print(mse)
print(np.mean(y), np.sqrt(mse), np.sqrt(mse)/np.mean(y))

287525.739635566
4503.676470588235 536.2142665349049 0.11906145346734216


$\mathbf{x} = [x_0, x_1, x_2, x_3]$ vs. $\mathbf{x} = [x_0, x_1]$

4503.676470588235 506.7945019577786 0.11252906492450268