# PyTorch Tensor

In [2]:
import torch
import numpy as np

## Initializing a Tensor

In [12]:
# From Python data

data = 1

x = torch.tensor(data)  # torch.int64

print(x.shape)
print(x.dim())
print(x.dtype)

print('x =', x)
print('x.data =', x.data)
print('x.grad =', x.grad)

print(x.item(), type(x.item()))

print(x.tolist(), type(x.tolist()))

torch.Size([])
0
torch.int64
x = tensor(1)
x.data = tensor(1)
x.grad = None
1 <class 'int'>
1 <class 'int'>


In [13]:
# From Python list

data = [1., 2.]

x = torch.tensor(data, requires_grad=True)  # turn on autograd; torch.float32

print(x.shape)
print(x.dim())
print(x.dtype)

print('x =', x)
print('x.data =', x.data)
print('x.grad =', x.grad)

# print(x.item(), type(x.item()))  # Error: a Tensor with 4 elements cannot be converted to Scalar

print(x.tolist(), type(x.tolist()))

torch.Size([2])
1
torch.float32
x = tensor([1., 2.], requires_grad=True)
x.data = tensor([1., 2.])
x.grad = None
[1.0, 2.0] <class 'list'>


In [14]:
# From Python list (set dtype)

data = [1, 2]

x = torch.tensor(data, dtype=torch.float)

print(x.shape)
print(x.dim())
print(x.dtype)

print('x =', x)
print('x.data =', x.data)
print('x.grad =', x.grad)

torch.Size([2])
1
torch.float32
x = tensor([1., 2.])
x.data = tensor([1., 2.])
x.grad = None


In [15]:
# From NumPy array

data = [[1., 2.], [3., 4.]]

data = np.array(data)  # float64

x = torch.tensor(data)

print(x.shape)
print(x.dim())
print(x.dtype)

print('x =', x)
print('x.data =', x.data)
print('x.grad =', x.grad)

data[0, 0] = 0.
print(data)
print(x)

torch.Size([2, 2])
2
torch.float64
x = tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
x.data = tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
x.grad = None
[[0. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [85]:
# From NumPy array

data = [[1., 2.], [3., 4.]]

data = np.array(data)  # float64

x = torch.from_numpy(data)

print('x =', x)
print('x.data =', x.data)
print('x.grad =', x.grad)

data[0, 0] = 0.
print(data)
print(x)

x = tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
x.data = tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
x.grad = None
[[0. 2.]
 [3. 4.]]
tensor([[0., 2.],
        [3., 4.]], dtype=torch.float64)


In [86]:
# To NumPy array

x = torch.ones((3, 4))

print('x =', x)
print('x.data =', x.data)
print('x.grad =', x.grad)

n = x.numpy()
print(x)

x[0] = 0
print(x)
print(n)

n[0] = 1
print(x)
print(n)

x = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
x.data = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
x.grad = None
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [87]:
# To NumPy array

x = torch.ones((3, 4), requires_grad=True) # turn on autograd

print('x =', x)
print('x.grad =', x.grad)

# n = x.numpy()  # Error: Can't call numpy() on Tensor that requires grad.

n = x.detach().numpy()

x = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
x.grad = None


## Attributes of a Tensor

In [89]:
tensor = torch.rand((3, 4))

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

In [90]:
# Standard numpy-like indexing and slicing

tensor = torch.ones((4, 4))
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [91]:
# Joining tensors

tensor = torch.ones((4, 4))

xx = torch.cat([x, x], dim=1)

print(xx.shape)

print(xx)

torch.Size([3, 8])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]], grad_fn=<CatBackward0>)


In [99]:
# Arithmetic operations

tensor = torch.ones((4, 4))

y1 = x @ x.T
print(y1)

y2 = x.matmul(x.T)
print(y2)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], grad_fn=<MmBackward0>)
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], grad_fn=<MmBackward0>)


In [101]:
x = torch.rand(3, 4)

agg = x.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

agg = x.mean()
agg_item = agg.item()
print(agg_item, type(agg_item))

agg = x.max()
agg_item = agg.item()
print(agg_item, type(agg_item))

6.701491355895996 <class 'float'>
0.558457612991333 <class 'float'>
0.9602238535881042 <class 'float'>
