### Numpy的随机模块

In [3]:
import numpy as np
# rand: 均匀分布 [0, 1)，参数是各维度大小
# randn: 标准正态分布（均值0，标准差1）
# randint: 随机整数 [low, high)
np.random.rand(3,2)

array([[0.61604098, 0.1498396 ],
       [0.09921105, 0.24025433],
       [0.47392118, 0.27707568]])

In [4]:
#返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4))

array([[4, 6, 8, 0],
       [0, 4, 6, 2],
       [4, 1, 7, 9],
       [5, 5, 5, 8],
       [5, 6, 8, 1]])

In [5]:
np.random.rand()

0.4411362842530916

In [7]:
np.random.random_sample()

0.5403150178394512

In [8]:
np.random.randint(0,10,3)

array([5, 9, 4])

In [9]:
#对于随机的高斯分布来说，mu为均值，sigma为标准差
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.11418809,  0.10804667,  0.21994074,  0.01997371, -0.05104641,
       -0.0218267 , -0.03796162,  0.04282013,  0.1259466 , -0.11949101])

In [38]:
#可以指定精度
np.set_printoptions(precision = 2)

In [39]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.01,  0.02,  0.12, -0.01, -0.04,  0.07,  0.14, -0.08, -0.01, -0.03])

In [ ]:
# 正态分布（自定义均值和标准差）
np.random.normal(loc=0, scale=1, size=(3, 3))     # 均值0，标准差1
np.random.normal(100, 15, 1000)                   # 1000个N(100,15²)

# 均匀分布（自定义范围）
np.random.uniform(low=0, high=10, size=5)         # [0,10)均匀分布

### 洗牌

In [11]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(tang_array)

In [13]:
tang_array

array([3, 6, 4, 0, 9, 1, 2, 8, 7, 5])

### 随机的种子

In [45]:
#生成随机数的时候，在没有种子的情况下，每个数都是以不同的方式随机的,那么每一次生成的结果都不一样
#计算机生成的随机数实际上是伪随机的（Pseudo-random）。它们由确定性的数学算法生成，种子就是这个算法的初始值。
#相同种子 → 完全相同的随机数序列
np.random.seed(100)
np.random.rand(3)

array([0.54340494, 0.27836939, 0.42451759])

In [40]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.16189817,  0.15416052, -0.02518791, -0.08424357,  0.01845187,
        0.09370822,  0.07310003,  0.13615561, -0.03262381,  0.0055676 ])

In [6]:
# choice: 从一维数组中随机抽取
np.random.choice([10, 20, 30], size=3)      # 抽取3个元素
np.random.choice(100, size=5, replace=False) # 0-99不重复抽取5个
np.random.choice(['a', 'b', 'c'], size=10, p=[0.5, 0.3, 0.2])  # 带权重抽取

array(['a', 'b', 'a', 'c', 'b', 'c', 'a', 'b', 'b', 'a'], dtype='<U1')

In [10]:
# 创建随机数生成器实例（推荐写法）
rng = np.random.default_rng(seed=42)

# 所有方法通过 rng 调用
rng.random((3, 2))            # 等同 rand，但参数需用元组
rng.standard_normal((3, 2))   # 等同 randn
rng.integers(0, 10, (3, 2))   # 等同 randint
rng.choice([1, 2, 3], size=2)
rng.shuffle(arr)