### 数组形状操作

In [2]:
import numpy as np
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
tang_array.shape

(10,)

In [4]:
tang_array.shape = 2,5
#将一个10数字的序列构造为2，5的格式

In [5]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小必须不能改变

In [7]:
tang_array .shape = 3,4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [8]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [9]:
tang_array = tang_array[np.newaxis,:]
#新增一个轴
tang_array.shape

(1, 10)

In [10]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [11]:
tang_array = tang_array[:,np.newaxis]
tang_array.shape

(10, 1)

In [12]:
tang_array = tang_array[:,np.newaxis,np.newaxis]
tang_array.shape

(10, 1, 1, 1)

In [13]:
tang_array = tang_array.squeeze()
#将多余的轴做一个压缩
tang_array.shape

(10,)

In [14]:
tang_array.shape = 2,5

In [15]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
tang_array.transpose()
#转置

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [17]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [18]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组的连接

In [33]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [34]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [36]:
c = np.concatenate((a,b))
#默认按照第一个维度
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [37]:
c = np.concatenate((a,b),axis = 0)
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [38]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [39]:
c.shape

(2, 6)

In [41]:
np.vstack((a,b))
#vstack就是表示在轴等于0，竖着拼接

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [42]:
np.hstack((a,b))
#hstack就是横着拼接

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [43]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [45]:
a.flatten()
#直接拉平

array([ 123,  456,  678, 3214,  456,  134])

In [46]:
a


array([[ 123,  456,  678],
       [3214,  456,  134]])

In [47]:
a.ravel()

array([ 123,  456,  678, 3214,  456,  134])