In [1]:
import numpy as np
tang_array = np.array([[1.5,1.3,7.5],
                      [5.6,7.8,1.2]])
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [12]:
np.sort(tang_array)
#sort默认从小到大排序，并且是从最后一个轴排序

array([[ 1.3,  1.5,  7.5],
       [ 1.2,  5.6,  7.8]])

In [13]:
np.sort(tang_array,axis = 0)

array([[ 1.5,  1.3,  1.2],
       [ 5.6,  7.8,  7.5]])

In [15]:
tang_array

array([[ 1.5,  1.3,  7.5],
       [ 5.6,  7.8,  1.2]])

In [14]:
np.argsort(tang_array)
#arg仍然是索引位置

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [2]:
tang_array = np.linspace(0,10,10)
#从0开始构造10个数，每两的差一样
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [3]:
values = np.array([2.5,6.5,9.5])

In [4]:
np.searchsorted(tang_array,values)
#为什么是3，6，9，解释如下：首先searchsort表示的是我在原数列中插入上述的2.5，6.5，9.5这些值，要求是必须先排序好

array([3, 6, 9])

In [5]:
tang_array = np.array([[1,0,6],
                       [1,7,0],
                       [2,3,1],
                       [2,4,0]])
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [31]:
index = np.lexsort([-1*tang_array[:,0],tang_array[:,2]])
#lexsort也是排序
index

array([0, 1, 3, 2], dtype=int64)

In [32]:
tang_array = tang_array[index]
tang_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])